apiVersion: v1
kind: Service
metadata:
  name: jam-ai-can-bot
  namespace: jam-ai-can-bot
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: jam-ai-can-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jam-ai-can-bot
  namespace: jam-ai-can-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jam-ai-can-bot
  template:
    metadata:
      labels:
        app: jam-ai-can-bot
    spec:
      containers:
        - name: jam-ai-can-bot
          image: andydevs/jam-ai-can-bot:latest
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: AgentEndpoint
metadata:
  name: jam-ai-can-bot
  namespace: jam-ai-can-bot
spec:
  bindings:
    - public
  upstream:
    url: http://jam-ai-can-bot.jam-ai-can-bot:80
  url: #$$NGROKDOMAINURL$$
